# Generated by Django 3.2.18 on 2023-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20230329_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('supper', 'Supper'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
