# Generated by Django 3.2.18 on 2023-04-10 14:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=tinymce.models.HTMLField(),
        ),
    ]
