# Generated by Django 3.2.18 on 2023-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(default='fake description', max_length=100),
            preserve_default=False,
        ),
    ]
