# Generated by Django 3.2.18 on 2023-04-14 13:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0016_alter_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=tinymce.models.HTMLField(),
        ),
    ]
