# Generated by Django 3.2.18 on 2023-05-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0018_alter_recipe_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
            ],
        ),
    ]
